// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhuehztcdzuwkzfytymu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1odWVoenRjZHp1d2t6Znl0eW11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTYyMTEsImV4cCI6MjA2NTUzMjIxMX0.fR3c-CKtGv_FEixBSmZr3f02ciE8NwjgIfHfc98kmn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});